import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = { // metadata for entire website SEO.
  title: "Create Next App",
  description: "Generated by create next app",
};
// one of main benefits of nextjs is you can improve SEO by serverside rendering your components and adding directly metadata to 
// to each of your pages.
// Helps with SEO, social sharing, and browser tab labeling

// creating new route go in app folder, create a

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
  {" "}
  <center><Link href={"/"}> Home </Link>
  <Link href={"/about"}> About </Link>
  <Link href={"/contact"}> Contact </Link>
  <Link href={"/users"}> Users </Link>
  </center>
</div>
        <h1>My Name is <b>John</b>Tom O'Callaghan</h1>
        <p>hello there how are you getting on</p>
    <a href="https://www.google.com">Google</a>
    <img
  src="https://www.jsg.utexas.edu/news/files/Dilophosaurus-Main.jpg"
  alt="Jurassic Park Dinosaur"
  style={{ maxWidth: "100%" }}
/>
// children is for each page and can add above and below it 
        {children}
        <center><p>testing bottom</p></center>
      </body>
    </html>
  );
}
